"""init

Revision ID: 1b00fb18112c
Revises: 
Create Date: 2025-07-28 15:02:52.062844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b00fb18112c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_migrations',
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date_insert', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_last_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('observability_user',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('celphone', sa.String(), nullable=True),
    sa.Column('document', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('non_confirmed', 'active', 'inactive', name='status_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date_insert', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_last_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observability_user')
    op.drop_table('admin_migrations')
    # ### end Alembic commands ###
